name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0' # every Sunday at midnight UTC

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]


    steps:
    - uses: actions/checkout@v3
    # Install libasound2-dev on Ubuntu runners
    - name: Install bevy deps on Ubuntu
      if: runner.os == 'linux'
      run: sudo apt-get install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
